name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/30 13-15 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1918741178@qq.com"
          git config --local user.name "PZ220V110W"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away. HAHAHA"
          git push
